/**
 * KAPSARC Circular Carbon Economy Index gateway mock.
 *
 * Serves the *published* CCE Index: 125 countries across 5 editions (2021-2025), a 46-node
 * indicator tree, and per-country/per-indicator readings. Data lives in four files under
 * mocks/kapsarc/, generated by backend/docs/data/kapsarc/extract.py --emit-mock so this mock and
 * the backend's record of last-known-good cannot drift apart.
 *
 * Note on `classification`: KAPSARC publishes numeric scores only. This mock returns null for it
 * and the consumer derives a band from its own configured thresholds. Emitting a label here would
 * silently override that.
 *
 * mocks/kapsarc/classifications.json is a *different* dataset — the curated 22-country CCE set,
 * whose `totalIndex` is a 1-22 standing rather than a 0-100 score. It is left alone.
 *
 * @swagger
 * tags:
 *   name: KAPSARC
 *   description: KAPSARC integration gateway operations
 */

/** Editions present in the dataset, ascending. */
function availableYears(editions) {
    return [...new Set((editions || []).map(e => e.indexYear))].sort((a, b) => a - b);
}

/** Resolve the requested edition, defaulting to the most recent. */
function resolveYear(raw, editions) {
    const years = availableYears(editions);
    if (raw === undefined || raw === '') {
        return { year: years[years.length - 1], years };
    }
    const parsed = Number.parseInt(raw, 10);
    if (Number.isNaN(parsed) || !years.includes(parsed)) {
        return { year: null, years };
    }
    return { year: parsed, years };
}

/** Index the readings by ISO-2 for one edition — one pass over ~29k rows instead of one per country. */
function readingsByCountry(readings, year) {
    const out = new Map();
    for (const r of readings || []) {
        if (r.year !== year) continue;
        let bucket = out.get(r.iso2);
        if (!bucket) { bucket = []; out.set(r.iso2, bucket); }
        bucket.push({
            indicatorCode: r.indicator,
            score: r.score,
            rank: r.rank,
            value: r.value,
            isImputed: r.imputed === true
        });
    }
    return out;
}

function factsFor(row) {
    if (!row) return null;
    return {
        populationMillions: row.populationMillions,
        landAreaSqKm: row.landAreaSqKm,
        gdpPerCapita: row.gdpPerCapita,
        gdpPerCapitaYear: row.gdpPerCapitaYear,
        incomeGroup: row.incomeGroup,
        regionalGroup: row.regionalGroup,
        isOilProducer: row.isOilProducer,
        isG20Member: row.isG20Member,
        isOecd: row.isOecd,
        isGcc: row.isGcc,
        latitude: row.latitude,
        longitude: row.longitude,
        cceIndexInceptionYear: row.cceIndexInceptionYear
    };
}

module.exports = {
    name: 'kapsarc-gateway',
    group: 'integrationgateway',
    description: 'Mock KAPSARC Circular Carbon Economy Index gateway — catalog, country facts, edition scores and indicator readings',
    endpoints: [
        {
            path: '/integrationgateway/kapsarc/classification',
            method: 'GET',
            mockDataKey: 'kapsarc-index-editions',
            behaviorKey: 'kapsarc-rules',
            description: 'Retrieve the CCE index reading for a single country',
            /**
             * @swagger
             * /integrationgateway/kapsarc/classification:
             *   get:
             *     summary: Get one country's CCE index reading
             *     tags: [KAPSARC]
             *     parameters:
             *       - in: query
             *         name: countryCode
             *         required: true
             *         schema: { type: string, example: "SAU" }
             *         description: ISO Alpha-3 country code
             *       - in: query
             *         name: countryName
             *         required: true
             *         schema: { type: string, example: "Saudi Arabia" }
             *         description: English country name
             *       - in: query
             *         name: year
             *         schema: { type: integer, example: 2025 }
             *         description: Index edition. Defaults to the most recent.
             *     responses:
             *       200:
             *         description: Index reading, or an error envelope when unavailable
             *         content:
             *           application/json:
             *             schema:
             *               type: object
             *               properties:
             *                 status: { type: string, example: "success" }
             *                 indexYear: { type: integer, example: 2025 }
             *                 classification: { type: string, nullable: true, example: null }
             *                 totalIndex: { type: number, example: 43.17 }
             *                 performanceScore: { type: number, example: 37.88 }
             *                 enablersScore: { type: number, example: 48.45 }
             *                 rank: { type: integer, example: 48 }
             *                 performanceRank: { type: integer, example: 71 }
             *                 enablersRank: { type: integer, example: 44 }
             *                 rankedCountryCount: { type: integer, example: 125 }
             */
            responseTransform: (req, editions, rules, mocks) => {
                const ruleResult = rules ? rules.check(req.query) : null;
                if (ruleResult) {
                    return { status: 'error', error: ruleResult.message };
                }

                const { year, years } = resolveYear(req.query.year, editions);
                if (year === null) {
                    return { status: 'error', error: `No CCE index data for year ${req.query.year}` };
                }

                const facts = (mocks['kapsarc-country-facts'] || []);
                const code = (req.query.countryCode || '').trim().toUpperCase();
                const name = (req.query.countryName || '').trim();

                // Editions are keyed on ISO-2; the caller sends ISO-3, so resolve through the facts
                // table, falling back to the English name.
                const fact = facts.find(f =>
                    (f.isoAlpha3 || '').toUpperCase() === code ||
                    (f.isoAlpha2 || '').toUpperCase() === code ||
                    (f.nameEn || '') === name);

                if (!fact) {
                    return { status: 'error', error: 'No CCE data available for country' };
                }

                const row = (editions || []).find(
                    e => e.isoAlpha2 === fact.isoAlpha2 && e.indexYear === year);

                if (!row) {
                    return { status: 'error', error: 'No CCE data available for country' };
                }

                return {
                    status: 'success',
                    indexYear: year,
                    availableYears: years,
                    countryCode: fact.isoAlpha3,
                    countryName: fact.nameEn,
                    classification: null,
                    totalIndex: row.totalIndex,
                    performanceScore: row.performanceScore,
                    enablersScore: row.enablersScore,
                    rank: row.rank,
                    performanceRank: row.performanceRank,
                    enablersRank: row.enablersRank,
                    rankedCountryCount: row.rankedCountryCount,
                    facts: factsFor(fact)
                };
            }
        },
        {
            path: '/integrationgateway/kapsarc/classifications',
            method: 'GET',
            mockDataKey: 'kapsarc-index-editions',
            description: 'Retrieve the full CCE index for one edition — catalog, countries, facts and indicator readings',
            /**
             * @swagger
             * /integrationgateway/kapsarc/classifications:
             *   get:
             *     summary: Get the full CCE index for one edition
             *     description: >
             *       Returns the indicator catalog plus every country's headline scores, publisher
             *       facts and per-indicator readings for a single edition (~800 KB). The response
             *       lists availableYears so a caller refreshing everything can loop the remaining
             *       editions without a separate discovery call.
             *     tags: [KAPSARC]
             *     parameters:
             *       - in: query
             *         name: year
             *         schema: { type: integer, example: 2025 }
             *         description: Index edition. Defaults to the most recent.
             *     responses:
             *       200:
             *         description: One edition of the index, or an error envelope
             *         content:
             *           application/json:
             *             schema:
             *               type: object
             *               properties:
             *                 status: { type: string, example: "success" }
             *                 year: { type: integer, example: 2025 }
             *                 availableYears:
             *                   type: array
             *                   items: { type: integer }
             *                   example: [2021, 2022, 2023, 2024, 2025]
             *                 rankedCountryCount: { type: integer, example: 125 }
             *                 indicators:
             *                   type: array
             *                   description: The 46-node indicator tree
             *                   items:
             *                     type: object
             *                     properties:
             *                       code: { type: string, example: "energy_efficiency" }
             *                       parentCode: { type: string, nullable: true }
             *                       level: { type: integer, example: 3 }
             *                       sortOrder: { type: integer }
             *                       nameEn: { type: string, example: "Energy efficiency" }
             *                       descriptionEn: { type: string, nullable: true }
             *                       unit: { type: string, nullable: true }
             *                       dataSource: { type: string, nullable: true }
             *                       dataSourceLink: { type: string, nullable: true }
             *                       weight: { type: number }
             *                       direction: { type: integer, example: 0 }
             *                       scorePrecision: { type: integer }
             *                 countries:
             *                   type: array
             *                   items:
             *                     type: object
             *                     properties:
             *                       countryCode: { type: string, example: "SAU" }
             *                       countryName: { type: string, example: "Saudi Arabia" }
             *                       classification: { type: string, nullable: true }
             *                       totalIndex: { type: number, example: 43.17 }
             *                       performanceScore: { type: number, example: 37.88 }
             *                       enablersScore: { type: number, example: 48.45 }
             *                       rank: { type: integer, example: 48 }
             *                       performanceRank: { type: integer, example: 71 }
             *                       enablersRank: { type: integer, example: 44 }
             *                       facts: { type: object }
             *                       indicators:
             *                         type: array
             *                         items:
             *                           type: object
             *                           properties:
             *                             indicatorCode: { type: string }
             *                             score: { type: number, nullable: true }
             *                             rank: { type: integer, nullable: true }
             *                             value: { type: number, nullable: true }
             *                             isImputed: { type: boolean }
             */
            responseTransform: (req, editions, _rules, mocks) => {
                const { year, years } = resolveYear(req.query.year, editions);
                if (year === null) {
                    return { status: 'error', error: `No CCE index data for year ${req.query.year}` };
                }

                const facts = mocks['kapsarc-country-facts'] || [];
                const indicators = mocks['kapsarc-indicators'] || [];
                const readings = readingsByCountry(mocks['kapsarc-indicator-readings'], year);
                const factsByIso2 = new Map(facts.map(f => [f.isoAlpha2, f]));

                const rows = (editions || []).filter(e => e.indexYear === year);
                const countries = rows.map(row => {
                    const fact = factsByIso2.get(row.isoAlpha2);
                    return {
                        countryCode: fact ? fact.isoAlpha3 : row.isoAlpha2,
                        countryName: fact ? fact.nameEn : null,
                        classification: null,
                        totalIndex: row.totalIndex,
                        performanceScore: row.performanceScore,
                        enablersScore: row.enablersScore,
                        rank: row.rank,
                        performanceRank: row.performanceRank,
                        enablersRank: row.enablersRank,
                        rankChange: null,
                        facts: factsFor(fact),
                        indicators: readings.get(row.isoAlpha2) || []
                    };
                });

                const total = rows.length > 0 ? rows[0].rankedCountryCount : null;

                return {
                    status: 'success',
                    year,
                    availableYears: years,
                    rankedCountryCount: total,
                    indicators,
                    countries
                };
            }
        }
    ]
};
